user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    sendfile on;
    tcp_nodelay on;
    tcp_nopush on;

    # Chuyển hướng lưu lượng HTTP sang iLO (Bypass SSL error)
    server {
        listen 80 default_server;
        server_name _;
        
        location / {
            proxy_pass https://192.168.100.2;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_ssl_verify off;
            proxy_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
            proxy_ssl_ciphers "HIGH:MEDIUM:LOW:EXP:!aNULL:!eNULL";
            proxy_ssl_server_name off;
            proxy_ssl_session_reuse off;
            
            proxy_set_header Host 192.168.100.2;
            proxy_set_header Origin https://192.168.100.2;
            proxy_set_header Referer https://192.168.100.2/;
            
            # Tắt nén để Nginx có thể dùng sub_filter viết lại gói tin
            proxy_set_header Accept-Encoding "";
            
            # Thay thế IP của iLO bằng IP của Proxy (Raspberry Pi)
            sub_filter '192.168.100.2' '192.168.100.7';
            sub_filter_once off;
            sub_filter_types *;
        }
    }

    # Chuyển hướng lưu lượng HTTPS (App Standalone) sang iLO
    server {
        listen 443 ssl default_server;
        server_name _;

        # Đường dẫn tới chứng chỉ Self-Signed tự tạo
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        location / {
            proxy_pass https://192.168.100.2;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_ssl_verify off;
            proxy_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
            proxy_ssl_ciphers "HIGH:MEDIUM:LOW:EXP:!aNULL:!eNULL";
            proxy_ssl_server_name off;
            proxy_ssl_session_reuse off;
            
            proxy_set_header Host 192.168.100.2;
            proxy_set_header Origin https://192.168.100.2;
            proxy_set_header Referer https://192.168.100.2/;
            
            proxy_set_header Accept-Encoding "";
            
            sub_filter '192.168.100.2' '192.168.100.7';
            sub_filter_once off;
            sub_filter_types *;
        }
    }
}
